// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaWebAPI.Data;

namespace SocialMediaWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210512191000_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialMediaWebAPI.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "I found a buffalo nickel!",
                            Likes = 0,
                            PostDate = new DateTime(2021, 5, 12, 14, 9, 59, 947, DateTimeKind.Local).AddTicks(5278),
                            Title = "Look what I found!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Mine is Groundhog Day",
                            Likes = 0,
                            PostDate = new DateTime(2021, 5, 12, 14, 9, 59, 953, DateTimeKind.Local).AddTicks(2502),
                            Title = "Whats your favorite movie?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
